# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wulf/HQfood/HQ_food/UI/month_report.ui'
#
# Created: Mon Oct  5 13:57:29 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_report(object):
    def setupUi(self, Dialog_report):
        Dialog_report.setObjectName(_fromUtf8("Dialog_report"))
        Dialog_report.resize(710, 644)
        self.layoutWidget = QtGui.QWidget(Dialog_report)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 11, 651, 611))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox_name = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_name.setObjectName(_fromUtf8("comboBox_name"))
        self.horizontalLayout.addWidget(self.comboBox_name)
        self.comboBox_date = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_date.setObjectName(_fromUtf8("comboBox_date"))
        self.horizontalLayout.addWidget(self.comboBox_date)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_1 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_1.setReadOnly(True)
        self.spinBox_1.setMaximum(10000)
        self.spinBox_1.setObjectName(_fromUtf8("spinBox_1"))
        self.gridLayout.addWidget(self.spinBox_1, 0, 2, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_2.setReadOnly(True)
        self.spinBox_2.setMaximum(10000)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout.addWidget(self.spinBox_2, 0, 4, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_3.setReadOnly(True)
        self.spinBox_3.setMaximum(10000)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout.addWidget(self.spinBox_3, 0, 6, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_4.setReadOnly(True)
        self.spinBox_4.setMaximum(10000)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout.addWidget(self.spinBox_4, 0, 8, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_5.setReadOnly(True)
        self.spinBox_5.setMaximum(10000)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout.addWidget(self.spinBox_5, 0, 10, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_6.setReadOnly(True)
        self.spinBox_6.setMaximum(10000)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout.addWidget(self.spinBox_6, 0, 12, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 11, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 9, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 7, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 13, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tableView = QtGui.QTableView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout.addWidget(self.tableView)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_7.setReadOnly(True)
        self.spinBox_7.setMaximum(10000)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_3.addWidget(self.spinBox_7, 0, 1, 1, 1)
        self.spinBox_8 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_8.setReadOnly(True)
        self.spinBox_8.setMaximum(10000)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.gridLayout_3.addWidget(self.spinBox_8, 0, 2, 1, 1)
        self.spinBox_9 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_9.setReadOnly(True)
        self.spinBox_9.setMaximum(10000)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.gridLayout_3.addWidget(self.spinBox_9, 0, 3, 1, 1)
        self.spinBox_10 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_10.setReadOnly(True)
        self.spinBox_10.setMaximum(10000)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.gridLayout_3.addWidget(self.spinBox_10, 0, 4, 1, 1)
        self.spinBox_11 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_11.setReadOnly(True)
        self.spinBox_11.setMaximum(10000)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.gridLayout_3.addWidget(self.spinBox_11, 0, 5, 1, 1)
        self.spinBox_12 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_12.setReadOnly(True)
        self.spinBox_12.setMaximum(10000)
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.gridLayout_3.addWidget(self.spinBox_12, 0, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_13 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_13.setReadOnly(True)
        self.spinBox_13.setMaximum(1000000)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.gridLayout_2.addWidget(self.spinBox_13, 0, 1, 1, 1)
        self.spinBox_14 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_14.setReadOnly(True)
        self.spinBox_14.setMaximum(1000000)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.gridLayout_2.addWidget(self.spinBox_14, 0, 2, 1, 1)
        self.spinBox_15 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_15.setReadOnly(True)
        self.spinBox_15.setMaximum(1000000)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.gridLayout_2.addWidget(self.spinBox_15, 0, 3, 1, 1)
        self.spinBox_16 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_16.setReadOnly(True)
        self.spinBox_16.setMaximum(1000000)
        self.spinBox_16.setObjectName(_fromUtf8("spinBox_16"))
        self.gridLayout_2.addWidget(self.spinBox_16, 0, 4, 1, 1)
        self.spinBox_17 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_17.setReadOnly(True)
        self.spinBox_17.setMaximum(1000000)
        self.spinBox_17.setObjectName(_fromUtf8("spinBox_17"))
        self.gridLayout_2.addWidget(self.spinBox_17, 0, 5, 1, 1)
        self.spinBox_18 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_18.setReadOnly(True)
        self.spinBox_18.setMaximum(1000000)
        self.spinBox_18.setObjectName(_fromUtf8("spinBox_18"))
        self.gridLayout_2.addWidget(self.spinBox_18, 0, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.spinBox_19 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_19.setReadOnly(True)
        self.spinBox_19.setMaximum(1000000000)
        self.spinBox_19.setObjectName(_fromUtf8("spinBox_19"))
        self.horizontalLayout_5.addWidget(self.spinBox_19)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog_report)
        QtCore.QMetaObject.connectSlotsByName(Dialog_report)

    def retranslateUi(self, Dialog_report):
        Dialog_report.setWindowTitle(_translate("Dialog_report", "每月結算", None))
        self.label.setText(_translate("Dialog_report", "$", None))
        self.label_2.setText(_translate("Dialog_report", "個別總量", None))
        self.label_3.setText(_translate("Dialog_report", "個別總收入", None))
        self.label_4.setText(_translate("Dialog_report", "本月收入", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog_report = QtGui.QDialog()
    ui = Ui_Dialog_report()
    ui.setupUi(Dialog_report)
    Dialog_report.show()
    sys.exit(app.exec_())

